name: build-deploy-cloudrun
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDP }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}
      - uses: google-github-actions/setup-gcloud@v2
      - name: Configure gcloud
        run: gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
      - name: Build image
        run: gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/quantumflow:latest
      - name: Deploy
        run: |
          gcloud run deploy quantumflow             --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/quantumflow:latest             --platform managed --region ${{ secrets.GCP_REGION }}             --allow-unauthenticated --memory 1Gi --cpu 1
